default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ksuser
  password: Latvia78
  host: localhost

development:
  <<: *default
  database: keepscore_development

test:
  <<: *default
  database: keepscore_test

production:
  <<: *default
  database: keep_score_production
  username: ksuser
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>
